### ISSUE TITLE
Switch language in the same tab

### ISSUE THREAD

**Issue by Carltoffel** [fortran-lang/fpm-docs#1]
When switching the language a new tab opens. I think it would be better to change the language in the same tab which is already open.

**Comment by awvwgk** [comment]
Currently I'm building to separate trees with sphinx and provide a mechanism to switch on the main page. An actual automatic switching would be great, but I haven't figured out yet how this can be implemented with sphinx. If you have an idea let me know.

**Comment by Carltoffel** [comment]
I went through some of the documentations using `sphinx` listed [here](https://www.sphinx-doc.org/en/master/examples.html) and the first one where I saw the option to change the language is the documentation of [calibre](https://manual.calibre-ebook.com/index.html). I couldn't find any source file where we could see how they do it, but maybe you have better luck. I don't know how automatic language switching could possibly work. Maybe there is some kind of information one could fetch from the browser or maybe even the locale?

**Comment by Carltoffel** [comment]
The `target="_blank"` attribute in the `href`s for switching the language cause the browser to open a new tab. To fix this simply remove them.
They are in the [pages/conf.py](https://github.com/awvwgk/fpm-docs/blob/03f2691ddd69c7c4d42b770018eafeec9ef761ea/pages/conf.py#L27) file.

**Comment by awvwgk** [comment]
The *calibre* docs using a similar trick, like I do with the `href`, I just found that this will only work for the toplevel, but not for any of the subpages. in the *calibre* docs there is only the toplevel, so they are mostly fine with this setup.
