### ISSUE TITLE
bug: website deploys before merging to main

### ISSUE THREAD

**Issue by gnikit** [fortran-lang/fpm-docs#129]
Currently the fpm documentation webpage deploys regardless of the branch we push from!

https://github.com/fortran-lang/fpm-docs/blob/e523247671c2af9c993ec5290c8ac6e95fab6dc7/.github/workflows/sphinx.yml#L49

This needs to be activated again ASAP!

**Comment by gnikit** [comment]
@perazz I was wondering was there a reason why you commented that part out in https://github.com/fortran-lang/fpm-docs/commit/fe4b1282bba1eedb703ff13a52b129143941b30e, or was it a quick way to test the deployment and forgot to change it back?

**Comment by perazz** [comment]
@gnikit, sorry for introducing that bug. I had commented that out to test the deployment of the docs on my fork and have failed to enable it back

**Comment by gnikit** [comment]
No worries, all fixed now. On the plus side it allowed for OpenMP to reference our how-to tutorial before it got merged in main, so I would say that it all worked out well in the end.
