### ISSUE TITLE
Use fpm logo

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm-docs#49]
@1984logo Do you have a source for the logo we can work with (svg, ...), I would make a start and incorporate it in the fpm documentation as favicon and sidebar logo.

Also, I plan to include a page on the logo itself and how it should be used in the design section.

From https://github.com/fortran-lang/fpm/discussions/380#discussioncomment-2079206

**Comment by 1984logo** [comment]
@awvwgk Sure, let me prepare the final files. I just posted an update there 

https://github.com/fortran-lang/fpm/discussions/380#discussioncomment-2134852.
If it is confirmed, I will prepare them.
