### ISSUE TITLE
Remove `❯` from code-blocks to make copy-pasted code runnable 

### ISSUE THREAD

**Issue by gnikit** [fortran-lang/fpm-docs#61]
I think that the fenced code-blocks in the docs might need to have the `❯` character removed, since copy-pasting the block results into the `❯` character being copied as well thus making the command unable to run upon paste

![image](https://user-images.githubusercontent.com/16143716/181034660-58daa315-87d6-4e58-a6a5-1823b918b9a3.png)

**Comment by awvwgk** [comment]
we can just exclude the prompt: https://sphinx-copybutton.readthedocs.io/en/latest/use.html#strip-and-configure-input-prompts-for-code-cells

**Comment by gnikit** [comment]
Ty @awvwgk
